/**
 * patchScript.js — generate Office Scripts (ExcelScript) patches from the dirty
 * registries.
 *
 * The app no longer writes the xlsx files. Each export produces a runnable
 * Office Script (one per file): a `main(workbook)` function that resolves
 * columns by header name, then applies the changes. Row lookup keys:
 *   - PS  → sheet "Form",         key EntityRef (unique)
 *   - DB  → sheet "ElementTypes",  key Ref (unique)
 *   - RS  → sheet "Form",         composite key ContextType+ContextRef+RecipeIndex+EntityRef
 *
 * Duplicates are resolved HERE (before generating): entries are coalesced to
 * one deterministic operation per target — update / append / soft-delete.
 */

// Canonical field → Excel column header (ported from backend/app.py).
const PS_FIELD_TO_EXCEL = {
  ElementTypeRef: 'EntityRef',
  Manufacturer: 'Manufacturer',
  ProductCode: 'ProductCode',
  ComponentDescription: 'ComponentDescription',
  InternalNotesText: 'InternalNotesText',
  IsTBC: 'IsTBC',
  IsDeleted: 'IsDeleted',
  IsPropertiesTBC: 'IsPropertiesTBC',
}

const RS_FIELD_TO_EXCEL = {
  ContextType: 'ContextType',
  ContextRef: 'ContextRef',
  RecipeIndex: 'RecipeIndex',
  ElementTypeRef: 'EntityRef',
  SortOrder: 'Sort Order',
  Quantity: 'Quantity',
  PackQuantity: 'PackQuantity',
  IsDeleted: 'IsDeleted',
  IsDesign: 'IsDesign',
  IsContractItem: 'IsContractItem',
  IsTRItem: 'IsTRItem',
  Dim_QuantityMultiplier: 'Dim_QuantityMultiplier',
  IsInteger: 'IsInteger',
}

const DB_FIELD_TO_EXCEL = {
  ElementTypeRef: 'Ref',
  Name: 'Name',
  Description: 'Description',
  Family: 'ParentRef',
  IsCollection: 'IsCollection',
  IsDeleted: 'IsDeleted',
  SortOrder: 'SortOrder',
}

// RS row objects may carry camelCase aliases; changedFields/before are PascalCase.
const RS_FIELD_ALIASES = {
  ContextType: 'contextType', ContextRef: 'contextRef', RecipeIndex: 'recipeIndex',
  ElementTypeRef: 'elementTypeRef', SortOrder: 'sortOrder', Quantity: 'quantity',
  PackQuantity: 'packQuantity', IsDeleted: 'isDeleted', IsDesign: 'isDesign',
  IsContractItem: 'isContractItem', IsTRItem: 'isTRItem',
  Dim_QuantityMultiplier: 'dimQtyMultiplier', IsInteger: 'isInteger',
}

const RS_KEY_FIELDS = ['ContextType', 'ContextRef', 'RecipeIndex', 'ElementTypeRef']
const NUMERIC_FIELDS = new Set(['RecipeIndex', 'Quantity', 'PackQuantity', 'SortOrder', 'Dim_QuantityMultiplier'])

function rsValue(row, field) {
  if (row[field] !== undefined) return row[field]
  const alias = RS_FIELD_ALIASES[field]
  return alias !== undefined ? row[alias] : undefined
}

function isBlank(v) {
  return v === null || v === undefined || (typeof v === 'string' && v.trim() === '')
}

/** setValue literal: numbers stay numeric, strings quote, blank -> null (-> .clear()). */
function literal(field, v) {
  if (isBlank(v)) return 'null'
  if (NUMERIC_FIELDS.has(field)) {
    const s = String(v).trim()
    if (/^-?\d+(\.\d+)?$/.test(s)) return s
  }
  if (typeof v === 'number') return String(v)
  return JSON.stringify(String(v))
}

const q = s => JSON.stringify(s)

// Top-level helpers, appended after main(). Office Scripts is TypeScript, so
// every parameter/return is typed with the ExcelScript.* type names.
const HELPERS = `function colMap(S: ExcelScript.Worksheet, names: string[]): { [key: string]: number } {
  const hdr = S.getCell(0, 0).getEntireRow();
  const m: { [key: string]: number } = {};
  for (const name of names) {
    const f = hdr.find(name, { completeMatch: true });
    m[name] = f ? f.getColumnIndex() : -1;
    if (m[name] < 0) console.log("WARNING: column not found: " + name);
  }
  return m;
}
function rowByKey(S: ExcelScript.Worksheet, keyCol: number, val: string): number {
  if (keyCol < 0) return -1;
  const f = S.getCell(0, keyCol).getEntireColumn().find(val, { completeMatch: true });
  return f ? f.getRowIndex() : -1;
}
function rowWhere(data: (string | number | boolean)[][], crit: { c: number; v: string }[]): number {
  for (let r = 1; r < data.length; r++) {
    let ok = true;
    for (const k of crit) {
      if (k.c < 0 || String(data[r][k.c]).trim() !== k.v) { ok = false; break; }
    }
    if (ok) return r;
  }
  return -1;
}
function writeCell(S: ExcelScript.Worksheet, r: number, c: number, v: string | number | null): void {
  if (c < 0 || r < 0) return;
  const cell = S.getCell(r, c);
  if (v === null) cell.clear(ExcelScript.ClearApplyTo.contents);
  else cell.setValue(v);
}`

/** Wrap the operation blocks in a runnable main() + helpers. USED is a placeholder. */
function wrapMain(filename, sheet, blocks, { needAppend, needData }) {
  if (blocks.length === 0) return ''
  const pre = [`    const S = workbook.getWorksheet(${q(sheet)});`, '    const col = colMap(S, USED);']
  if (needData) pre.push('    const data = S.getUsedRange().getValues();')
  if (needAppend) pre.push('    let apR = S.getUsedRange().getRowCount();')
  return (
    `// Patch for ${filename} - generated by Recipe Builder.\n` +
    `// Paste into Excel: Automate tab -> New Script -> paste -> Run.\n\n` +
    'function main(workbook: ExcelScript.Workbook) {\n' +
    '  try {\n' +
    pre.join('\n') + '\n\n' +
    blocks.join('\n\n') + '\n\n' +
    `    console.log(${q(filename + ' patch complete.')});\n` +
    '  } catch (e) {\n    console.log("Script error: " + e);\n    throw e;\n  }\n}\n\n' +
    HELPERS + '\n'
  )
}

/** Replace the USED placeholder with the array of header names actually touched. */
function fillUsed(script, used) {
  return script.replace('USED', `[${[...used].map(q).join(', ')}]`)
}

// --- PS / DB (unique-key) -------------------------------------------------
function buildUniqueKeyScript(changes, map, sheet, keyHeader, filename, { withEntityType }) {
  const byRef = new Map()
  for (const e of changes || []) byRef.set(e.elementTypeRef, e)   // coalesce, last wins

  const used = new Set([keyHeader])
  const blocks = []
  let needAppend = false

  for (const [ref, entry] of byRef) {
    if (!ref) continue
    const updates = entry.updates || {}
    const isNew = !!entry._isNew
    if (isNew && updates.IsDeleted === 'Y') continue   // created then deleted -> no-op

    const fields = Object.entries(updates).filter(([f]) => f !== 'ElementTypeRef' && map[f])

    if (isNew) {
      needAppend = true
      const l = [`    // add ${ref}`, `    writeCell(S, apR, col[${q(keyHeader)}], ${q(ref)});`]
      if (withEntityType) { used.add('EntityType'); l.push('    writeCell(S, apR, col["EntityType"], "ElementType");') }
      for (const [f, v] of fields) {
        if (isBlank(v)) continue   // blank on a fresh row = leave empty
        used.add(map[f])
        l.push(`    writeCell(S, apR, col[${q(map[f])}], ${literal(f, v)});`)
      }
      l.push('    apR++;')
      blocks.push(l.join('\n'))
    } else {
      if (fields.length === 0) continue
      const l = [`    // update ${ref}`, '    {',
        `      const r = rowByKey(S, col[${q(keyHeader)}], ${q(ref)});`,
        `      if (r < 0) { console.log(${q('WARNING: ' + ref + ' not found - skipped.')}); }`,
        '      else {']
      for (const [f, v] of fields) {
        used.add(map[f])
        l.push(`        writeCell(S, r, col[${q(map[f])}], ${literal(f, v)});`)
      }
      l.push('      }\n    }')
      blocks.push(l.join('\n'))
    }
  }

  return fillUsed(wrapMain(filename, sheet, blocks, { needAppend, needData: false }), used)
}

export function buildPsScript(psChanges, filename = 'Product Spec') {
  return buildUniqueKeyScript(psChanges, PS_FIELD_TO_EXCEL, 'Form', 'EntityRef', filename, { withEntityType: true })
}

export function buildDbScript(dbChanges, filename = 'ElementTypes (DB)') {
  return buildUniqueKeyScript(dbChanges, DB_FIELD_TO_EXCEL, 'ElementTypes', 'Ref', filename, { withEntityType: false })
}

// --- RS (composite-key) ---------------------------------------------------
function rsNaturalKey(entry) {
  const row = entry.row || {}
  const before = entry.before || {}
  // Prefer the ORIGINAL key so an edit still locates its on-disk row.
  return RS_KEY_FIELDS.map(f => {
    const v = before[f] !== undefined ? before[f] : rsValue(row, f)
    return v == null ? '' : String(v)
  })
}

/** [{ c: col[Header], v: "value" }, ...] criteria array for rowWhere. */
function rsCriteria(entry) {
  const row = entry.row || {}
  const before = entry.before || {}
  const parts = RS_KEY_FIELDS.map(f => {
    const v = before[f] !== undefined ? before[f] : rsValue(row, f)
    return `{ c: col[${q(RS_FIELD_TO_EXCEL[f])}], v: ${q(v == null ? '' : String(v))} }`
  })
  return `[${parts.join(', ')}]`
}

export function buildRsScript(rsChanges, filename = 'Recipe Spec') {
  // Coalesce by natural key (resolve duplicates in the tool): last wins,
  // and skip unresolved template slots (held back from export, T-E4).
  const byKey = new Map()
  for (const e of rsChanges || []) {
    const row = e.row || {}
    if (row.resolved === false) continue
    byKey.set(rsNaturalKey(e).join(' '), e)
  }

  const used = new Set(RS_KEY_FIELDS.map(f => RS_FIELD_TO_EXCEL[f]))
  const appendBlocks = []
  const otherBlocks = []
  let needAppend = false
  let needData = false

  for (const entry of byKey.values()) {
    const action = entry.action || 'upsert'
    const row = entry.row || {}
    const isAppend = action === 'upsert' && !row._row_num && !entry.changedFields

    if (action === 'delete') {
      needData = true
      used.add('IsDeleted')
      otherBlocks.push(
        '    {\n' +
        `      const r = rowWhere(data, ${rsCriteria(entry)});\n` +
        '      if (r < 0) { console.log("WARNING: recipe row not found - skipped."); }\n' +
        '      else { writeCell(S, r, col["IsDeleted"], "Y"); }\n    }'
      )
    } else if (isAppend) {
      needAppend = true
      used.add('EntityType')
      const l = ['    // add recipe row', '    writeCell(S, apR, col["EntityType"], "ElementType");']
      for (const f of Object.keys(RS_FIELD_TO_EXCEL)) {
        const v = rsValue(row, f)
        if (isBlank(v)) continue
        used.add(RS_FIELD_TO_EXCEL[f])
        l.push(`    writeCell(S, apR, col[${q(RS_FIELD_TO_EXCEL[f])}], ${literal(f, v)});`)
      }
      l.push('    apR++;')
      appendBlocks.push(l.join('\n'))
    } else {
      const changed = entry.changedFields || {}
      const fields = Object.entries(changed).filter(([f]) => RS_FIELD_TO_EXCEL[f])
      if (fields.length === 0) continue
      needData = true
      const l = ['    {', `      const r = rowWhere(data, ${rsCriteria(entry)});`,
        '      if (r < 0) { console.log("WARNING: recipe row not found - skipped."); }',
        '      else {']
      for (const [f, v] of fields) {
        used.add(RS_FIELD_TO_EXCEL[f])
        l.push(`        writeCell(S, r, col[${q(RS_FIELD_TO_EXCEL[f])}], ${literal(f, v)});`)
      }
      l.push('      }\n    }')
      otherBlocks.push(l.join('\n'))
    }
  }

  const blocks = [...otherBlocks, ...appendBlocks]
  return fillUsed(wrapMain(filename, 'Form', blocks, { needAppend, needData }), used)
}
