/**
 * changelog.js — the one-line "what changed" shown on the start page.
 *
 * It exists so a fresh deploy is visibly distinguishable: if the top line's date/note
 * moved, you are looking at a new build (past a stale cache). Newest first; add ONE line
 * whenever you ship something user-facing. Keep each note short — it renders on a single
 * line under the title.
 */
export const CHANGELOG = [
  { date: '2026-09-28', note: 'Fixes from bug reports: point-source mounting/frames no longer costed by length; a family row (ET-DRIVERS) is never offered as a product, and Recipes from the Form says which Form code a row came from; connector templates offer the project’s own tags; Import resumes after adding to the Product Spec; Product Spec can change an ElementType’s family and ref' },
  { date: '2026-09-28', note: 'Import: “First: confirm 1 row, then give N codes an ElementType” — each part is a link to what is blocking. In the ElementTypes window an unticked code says it is left without one, and offers “Not a code” (its words become a note) and “Show its rows”' },
  { date: '2026-09-28', note: 'Bug reports: the bug beside ALPHA turns them on; right-click anything to write a note, saved with where you were (screen, window, what you clicked, refs, last clicks). Copy or save them all as Markdown from the bug’s ▾ or the export window' },
  { date: '2026-09-28', note: 'Existing ElementTypes: tick some and “Move to family” — renumbered into it (ET-PS-03 → ET-PS-MOUNTING-FRAME-01) through the Product Spec and Recipes, the family created if missing' },
  { date: '2026-09-28', note: 'Import product codes: a “TBC” marked as a code is a TBC placeholder (no more stuck “1 code needs an ElementType”); Add to Product Spec waits until every row is confirmed and has an ElementType (adding part is in ⋯); products are never proposed into ET-DL / ET-LIN, extras (frames, louvres) no longer follow the luminaire into ET-PS' },
  { date: '2026-09-28', note: 'Review recipes: filter with rules on any field (all / any), “matches” takes wildcards (* ? , and ! for not); save filter sets per project; results table with your own columns, sortable, click a row to start there' },
  { date: '2026-09-28', note: 'Recipe view: the PositionTypes list stays open as a left sidebar (ref + status dot, ↑ / ↓ to move, collapsible, resizable); list options — filters, sort, ignored, tags, Review empty, Tag changes — are in its ⋯' },
  { date: '2026-09-28', note: 'One help button per header: the Form spec and export windows had two; the tutorial now opens with the key idea, and the Form pane’s ⋯ has "What is this?"' },
  { date: '2026-09-27', note: 'Fixed: the DesignDB patch would not run in Office Scripts ("Only arrow functions may be used in array method callbacks")' },
  { date: '2026-09-27', note: 'Fixed: the DesignDB patch used Excel’s sort, which on a sheet whose filter / Table covers only some columns left the rest (InternalNotesText…) on other rows. Rows are now moved whole by the script. Restore a DesignDB patched with the previous version from its version history' },
  { date: '2026-09-27', note: 'DesignDB patch: ElementTypes in tree order (each family, then its members, by Ref — ET-CABLES 1, LC1 2 …), natural Ref order (LC2 before LC11)' },
  { date: '2026-09-27', note: 'DesignDB patch: only family rows (named as another row’s ParentRef) turn purple; wrappers (ET-DL-NN, ET-LIN-NN) stay plain, and ones painted by the last patch are cleared' },
  { date: '2026-09-27', note: 'An ALPHA badge on every page' },
  { date: '2026-09-27', note: 'DesignDB patch: ElementTypes sorted by ParentRef > Ref with SortOrder 1..N, collection rows purple / white bold. TBC placeholders get ordinary refs. Setting up a group asks you to confirm clip / tape / profile / mount / cap quantities (pulsing). Import resumes by itself; Re-import and Learned this project are in ⋯' },
  { date: '2026-09-27', note: 'Exterior only when the DesignDB family says EXTERIOR (in-ground / IP-rated are no longer taken as exterior); IP-rated connectors are never proposed — left for review' },
  { date: '2026-09-27', note: 'Recipes from the Form: one group per kind (wrapper · driver · interior/exterior), not per mix of ingredients; the richest position is set up first. 5452: 5 groups instead of 13' },
  { date: '2026-09-27', note: 'Fixed: clips, tape, profiles and caps (ET-LIN-CLIP-01…) were taken for wrappers and specced Ideaworks N/A — only a numbered ET-DL-NN / ET-LIN-NN is a wrapper; "Fix them" puts affected parts back. Recipes add only what you tick: parts borrowed from elsewhere start unticked' },
  { date: '2026-09-27', note: 'Recipes from the Form: the wrapper is your call per group (DL / LIN / none — precedent is only the default), and each part can ship inside it or separately; "Use it again" re-teaches a group' },
  { date: '2026-09-27', note: 'Setting up a group no longer strands you in the builder: a bar says which group, what is still empty on its first position, and brings you back — "Use it for the other N" goes straight to the rest, ticked' },
  { date: '2026-09-27', note: 'Recipes from the Form, redone: positions grouped by kind (from the DesignDB); the first of each group proposed per process.md and precedent (this project, projects opened before, 4343) with every row sourced and unknown parts left empty; you check it, then the rest copy it with their own products, sharing wrappers' },
  { date: '2026-09-27', note: 'Track: ET-TRACK (the track) and ET-TRACK-PS (fittings on it), from the DesignDB’s TRACK positions; recipes as 4343 builds them' },
  { date: '2026-09-27', note: 'A new project says where to start (Import the Form), then offers to build what it imported' },
  { date: '2026-09-27', note: 'Build recipes from the Form: templates saved from a recipe now carry each position\'s own Form products; one window builds every imported position (template, products only, or skip), one Undo' },
  { date: '2026-09-27', note: 'TBC, custom and "awaiting" rows get a placeholder Product Spec row (TBC) and an ElementType of their own; n/a and by-others stay nothing to add' },
  { date: '2026-09-27', note: 'Import opens pre-filled: codes from this spec and every project opened before are painted (with their ElementType), and code-shaped words are pre-selected (dashed). Your paint and taught rules always win; Undo all clears it' },
  { date: '2026-09-27', note: 'Known product lines file themselves: Atea NEO and Tryka Continuity are flexible linear, Forma Microline and Flos Glowing Track are fixed linear' },
  { date: '2026-09-27', note: 'Better ElementType families on import: old LEDFlex codes still file by kind, rails are mounts, casings and back boxes are point mounting, louvres and glare shields are accessories; notes stay with their own code in ";" and "," lists' },
  { date: '2026-09-27', note: 'Import needs less teaching: maker codes are spotted untaught, TBC / n/a / by-specialist rows say "nothing to add", Confirm obvious takes "+" extras, Accessories words stay off the main code, and wording-only note differences no longer block' },
  { date: '2026-09-27', note: 'Import product codes, reworked: paint a few rows, then work in the Form as a table (click words, tick rows, Confirm obvious, full undo); refs match silently; one ElementTypes window; Add to Product Spec → Build recipes' },
  { date: '2026-09-27', note: 'Simpler UI: one Add panel with one search; one ElementTypes window (New / Existing / Unused); one status chip style; recipe header actions in a menu; obvious import columns skip their step; tutorials only open from ?' },
  { date: '2026-09-27', note: 'Less reading: explanations moved behind ⓘ icons (hover or tap) across the start page, import, Form pane and most windows' },
  { date: '2026-09-27', note: 'Projects: Restore from backup straight from the start page; "Configuration" is now a Setup, shown only when a folder has more than one; Save backup in the builder menu and on Close project' },
  { date: '2026-09-27', note: 'Templates start from a real recipe: the bookmark button saves a position as a template (untick rows, choose tags); Apply to… fills many positions at once, each with its own new wrapper' },
  { date: '2026-09-27', note: 'The save indicator is now a laptop: work is kept on this computer until you export' },
  { date: '2026-09-27', note: 'Fixed: templates save again — project templates were stored under no project, fields were encoded twice, and "Save as new" never appeared' },
  { date: '2026-09-25', note: 'Import product codes: a Form\'s Accessories column is read too (found automatically), its codes becoming extras on the same position; "-" is ignored' },
  { date: '2026-09-25', note: 'Review all existing ElementTypes: every ET by family, unfiled first, with product and usage; edit Name, Description and Family, saved in one go' },
  { date: '2026-09-25', note: 'Save indicator (cloud) beside the project; Ctrl+S saves now and says what is still to export. Close project asks first; Back undoes Next' },
  { date: '2026-09-25', note: 'Every recipe gets one IsDesign item as you leave it: a lone row is marked for you, otherwise you pick one before moving on' },
  { date: '2026-09-25', note: 'A row has Quantity OR Dim_QuantityMultiplier, never both; profiles default to a multiplier of 1. Tutorials no longer stack over other windows' },
  { date: '2026-09-25', note: 'Side-by-Side: a position with no wrapper offers + LIN wrapper / + DL wrapper (next free ET-LIN-NN / ET-DL-NN, Ideaworks N/A), so Form products can go inside it' },
  { date: '2026-09-25', note: 'Fixed: a code typed without its dashes (NFS240272009) matches its known shape, so LEDFlex tape is no longer filed as profile; a note naming two kinds of product is flagged' },
  { date: '2026-09-25', note: 'Fixed: adding from the Form no longer lands on another position when a wrapper recipe was open earlier' },
  { date: '2026-09-25', note: 'Side-by-Side: add a missing Form product in one click (+ Position / + in wrapper), Add all, Undo; Next when a position is done' },
  { date: '2026-09-25', note: 'Import: Stage sits on top and turns green when every code is done; pills say in spec / variant / repeated / new. Review: Next bottom-right, Close moved left, ← → keys' },
  { date: '2026-09-25', note: 'New ElementTypes review: drag a code by its grip (or its ⇄ menu) into another family, add your own family; refs renumber. A green tick replaces the repeated reason text' },
  { date: '2026-09-25', note: 'Style library: every project you open teaches the tool how its products were named; new ElementTypes copy that style, flagged "check ref" when unsure' },
  { date: '2026-09-25', note: 'New ElementTypes use the company families (ET-PS, ET-LIN-TAPE/PROF/DIFF…), from the Form page type, product words and a table of known code shapes; old LEDFlex numbering is flagged' },
  { date: '2026-09-25', note: 'Import product codes: review every new ElementType at once, named by family (ET-PS-08) as "Maker - Code"; near-miss codes show a diff, not a %' },
  { date: '2026-09-25', note: 'Import product codes: line breaks split codes, lone + - / are discarded, no more phantom "**" codes; copy buttons and Form columns at the top' },
  { date: '2026-09-25', note: 'A config can read several DesignDBs (tick each one); config YAML now saves the file pairing and unexported changes, and can restore a config' },
  { date: '2026-09-25', note: 'Fixed: a Product Spec with an all-digit ProductCode no longer fails to open; big workbooks with scratch sheets open much faster' },
  { date: '2026-07-13', note: 'Fork a position: copy its recipe into new position type(s), each with its own wrapper, untick the rows to drop — in one step' },
  { date: '2026-07-13', note: 'Clean up unused ElementTypes now also catches Product Spec orphans no recipe uses (e.g. ET-PS-14), cascading to the DesignDB if present' },
  { date: '2026-07-13', note: 'Clean up unused ElementTypes: retire the ones only used by excluded or unplaced positions, across all three workbooks' },
  { date: '2026-07-13', note: 'Copy/paste keeps a row’s flags and quantity, and no longer offers to merge a position-level row into a wrapper' },
  { date: '2026-07-13', note: 'Every recipe row is now design-or-contract: new rows default to contract, and a validation fix clears any blanks' },
  { date: '2026-07-13', note: 'Tidier recipe toolbar: a Connectors button straight to the matrix, rare actions folded into a menu, broken tree Status toggle removed' },
  { date: '2026-07-12', note: 'Fixed: editing a quantity (or any field) on an existing recipe row now actually reaches the export patch' },
  { date: '2026-07-12', note: 'Status tutorial rebuilt: the real two-tab modal, the readiness clauses, and validation as task cards' },
  { date: '2026-07-12', note: 'Retired the old connector wizard: all connectors now go through Connector Templates and the coverage matrix' },
  { date: '2026-07-12', note: 'Tutorial cards now open in a declared order (recipe before palette), and the palette card looks like the actual drawer' },
  { date: '2026-07-12', note: 'Connector tutorial rebuilt: it now starts from an empty screen and MAKES a template, then shows the real matrix table' },
  { date: '2026-07-12', note: 'Side-by-Side refresh: reference behind an icon rail, a ⋮ menu, per-row status icons, and Form/recipe divergence visible without hovering' },
  { date: '2026-07-12', note: 'Painting is now taught properly: a real 4-product linear cell, painted step by step — notes, learned delimiters, suggested codes' },
  { date: '2026-07-12', note: 'Import + Product Spec tutorials rebuilt: drag-a-brush over continuous text, and the real split-panel browser/editor' },
  { date: '2026-07-12', note: 'Strain-relief warning no longer fires on positions with no connectors; tutorial scenes rebuilt against the real rendered DOM' },
  { date: '2026-07-12', note: 'Tutorial scenes now mirror the real panes and use the real refs (A02m, C01r, ET-LIN-01) — the pointer is anchored, not guessed' },
  { date: '2026-07-12', note: 'Every pane now has a tutorial card: auto-opens once, replays from the ? chip, an animated demo of what the pane can do' },
  { date: '2026-07-11', note: 'New landing page: it IS the project list. Re-picking a folder no longer forks a duplicate; projects can be named' },
  { date: '2026-07-11', note: 'Form spec: a pending product can be merged into an ElementType the recipe already has, instead of only "Create"' },
  { date: '2026-07-11', note: 'Removed the old built-in "Connector Sets" templates (2/3/4/5-Pin × Local/Remote) — the Connectors screen owns that' },
  { date: '2026-07-11', note: 'Built-in templates drop their connector slots — the connector wizard owns sockets, plugs and strain reliefs now' },
  { date: '2026-07-11', note: '"Like this" palette tab: when the Form is silent on a position, compare and borrow rows from comparable ones' },
  { date: '2026-07-11', note: 'Builder: the duplicate Navigator drawer is gone; palette opens with a position; Validation + Done? are one Status button' },
  { date: '2026-07-11', note: 'Validation no longer demands a socket/strain-relief on projects that use no connectors' },
  { date: '2026-07-11', note: 'Fix-validation step can flag a position (or its family) as "no recipe needed" right there' },
  { date: '2026-07-11', note: 'Recipe rows: one fork icon everywhere; shared-ET is a quiet icon, and never doubles up inside a wrapper' },
  { date: '2026-07-11', note: 'Import: stage result pops a modal; shared-ElementType fork lives in the builder' },
  { date: '2026-07-11', note: 'Fixed the DesignDB patch freeze, the dev sql.js load, and identical sort orders' },
]

export const LATEST = CHANGELOG[0]
